-- 1. 先确保项目存在
INSERT INTO projects (id, name, code, description) 
VALUES 
  ('11111111-1111-1111-1111-111111111111', '北戴河海宸府', 'haichen', '高端海景住宅'),
  ('22222222-2222-2222-2222-222222222222', '北京山谷', 'shangu', '山景别墅社区')
ON CONFLICT (code) DO NOTHING;

-- 2. 插入北戴河海宸府 (haichen) 的规则
INSERT INTO rules (project_id, type, keyword, reason, suggestion) 
SELECT id, 'violation', '国家级', '绝对化用语，涉嫌虚假宣传', '删除或替换为具体认证信息' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '最高级', '绝对化用语，禁止使用', '改为客观描述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '最佳', '绝对化用语，禁止使用', '改为具体优势描述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '唯一', '绝对化用语，禁止使用', '如无法证实请删除' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '史上最强', '绝对化用语，禁止使用', '删除或改为具体数据' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '零风险', '绝对化用语，禁止使用', '删除或改为客观描述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', 'zui', '绝对化用语变体（最）', '使用标准汉字' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '最', '绝对化用语："最"字属于夸大宣传', '删除或改为具体描述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '蕞', '绝对化用语变体（最）', '使用标准汉字' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '极致', '绝对化用语，禁止使用', '改为具体描述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '超绝', '绝对化用语，禁止使用', '删除或改为客观描述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '包下证', '虚假承诺，涉嫌违规', '删除此类承诺' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '包授权', '虚假承诺，涉嫌违规', '删除此类承诺' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '快速见效', '虚假/夸大承诺', '删除或改为客观描述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '100%有效', '绝对化承诺，涉嫌虚假宣传', '删除绝对化表述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', 'guaranteed', '英文绝对化用语', '删除或改为客观描述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '当天见效', '夸大承诺，涉嫌虚假', '删除时间承诺' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '无副作用', '虚假承诺，医疗相关', '删除此类表述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '国家知识产权局指定', '冒用官方/权威身份', '如无资质请删除' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '政府推荐', '冒用官方身份', '如无资质请删除' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '专家推荐', '冒用权威身份（无资质）', '删除或注明真实身份' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '院士推荐', '冒用权威身份（无资质）', '删除或注明真实身份' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '不买就落后', '贩卖焦虑类表述', '删除焦虑营销内容' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '孩子输在起跑线', '贩卖焦虑类表述', '删除焦虑营销内容' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '30岁还不', '贩卖焦虑类表述', '删除年龄焦虑内容' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '容貌崩坏', '贩卖焦虑/医疗夸大', '删除此类表述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '不孕不育', '医疗敏感类内容', '删除此类表述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', 'yyds', '平台拦截的网络用语', '使用规范表达' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', 'dbq', '平台拦截的网络用语', '使用规范表达' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', 'nsdd', '平台拦截的网络用语', '使用规范表达' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', 'ssmy', '平台拦截的网络用语', '使用规范表达' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '赚米', '平台拦截的变体词汇', '使用规范表达' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '浮力', '平台拦截的变体词汇（福利）', '使用标准汉字' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '保本', '金融特许行业禁用词', '删除此类金融表述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '高回报', '金融特许行业禁用词', '删除此类金融表述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '内部名额', '特许行业禁用词', '删除此类表述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'violation', '包就业', '教育特许行业禁用词', '删除此类承诺' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'throttling', '限时优惠', '限流敏感词，容易被平台限流', '改为"近期活动"或"专属优惠"' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'throttling', '立即抢购', '限流敏感词，催促购买语气过强', '改为"了解更多"' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'throttling', '马上涨价', '制造紧迫感，容易限流', '删除制造焦虑的表达' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'throttling', '错过不再', '制造紧迫感，容易限流', '删除此类表达' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'throttling', '全网最低', '绝对化表述，容易限流', '改为具体价格优势描述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'throttling', '亏本销售', '虚假促销表述，容易限流', '删除此类表述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'throttling', '超级划算', '主观夸大表述，容易限流', '改为具体优势描述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'throttling', '绝对不亏', '绝对化表述，容易限流', '删除此类表述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'throttling', '拎包入住', '限流敏感词：暗示简单装修即可入住，品质感低', '改为"精装修交付"或"配套完善"' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'throttling', '老破小', '限流敏感词：负面描述房产，可能引发用户反感', '删除此类表述，改为客观描述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'throttling', '残疾人', '限流敏感词：利用弱势群体进行悲情营销', '删除此类内容，避免悲情营销' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'throttling', '弱势群体', '限流敏感词：利用弱势群体进行悲情营销', '删除此类内容，保持正向积极' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'throttling', '卖惨', '限流敏感词：利用悲情营销获取关注', '删除此类内容，改用正向积极表达' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'throttling', '可怜', '限流敏感词：悲情营销，容易引发用户反感', '删除此类表述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'suggestion', '物价低', '引流风险：描述当地物价低可能吸引价格敏感用户', '避免强调低价，结合品质和体验进行描述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'suggestion', '生活成本低', '引流风险：强调生活成本低可能引流到价格敏感用户', '改为强调生活品质和性价比' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'suggestion', '便宜', '引流风险：直接强调"便宜"可能吸引价格敏感用户', '改为"高性价比"或"物超所值"' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'suggestion', '几块钱', '引流风险：描述"几块钱"等低价信息容易引流到价格敏感用户', '删除具体价格描述，改为品质导向' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'suggestion', '超便宜', '引流风险：强调超便宜会吸引价格敏感用户', '改为"高性价比"描述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'suggestion', '白菜价', '引流风险：使用"白菜价"引流到价格敏感用户', '删除此类低价表述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'suggestion', '物价便宜', '引流风险：强调物价便宜会吸引价格敏感用户', '改为强调当地生活品质' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'suggestion', '海鲜便宜', '引流风险：强调"海鲜便宜"等本地物价可能吸引价格敏感用户', '改为强调海鲜品质和新鲜度' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'suggestion', '青菜便宜', '引流风险：强调青菜便宜等日常消费低会引流到价格敏感用户', '删除此类表述' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'suggestion', '省钱', '引流风险：强调省钱会吸引价格敏感用户', '改为强调价值而非价格' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'suggestion', '低成本', '引流风险：强调低成本生活会吸引价格敏感用户', '改为强调生活品质' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'suggestion', '9900万', '数据限制：北戴河客流数字不能说大于9900万', '调整为不超过9900万的数字' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'suggestion', '1亿', '数据限制：北戴河客流不能说大于9900万', '核实具体数字，确保不超过9900万' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'suggestion', '30多个', '数据限制：北戴河景区数量不能说大于30多个', '调整为不超过30个' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'suggestion', '5A级', '合规限制：北戴河不能说5A级景区，只能说A级景区', '删除"5A"，改为"A级景区"' FROM projects WHERE code = 'haichen'
UNION ALL SELECT id, 'suggestion', '5A景区', '合规限制：北戴河不能说5A级景区，只能说A级景区', '删除"5A"，改为"A级景区"' FROM projects WHERE code = 'haichen';

-- 3. 插入北京山谷 (shangu) 的规则
INSERT INTO rules (project_id, type, keyword, reason, suggestion) 
SELECT id, 'violation', '床', '居家信息：北京山谷为商用住宅，禁止出现居住相关描述', '删除"床"相关描述，可改为"办公区"或"功能区"' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '卧室', '居家信息：商用住宅不允许出现卧室描述', '删除或改为"独立空间"' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '厨房', '居家信息：商用住宅禁止出现厨房描述', '删除或改为"料理区"或"餐饮区"' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '住', '居家信息：商用住宅不允许出现"住"相关描述', '删除居住相关表述，改为办公或商用描述' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '住宿', '居家信息：商用住宅禁止住宿描述', '删除或改为"短租"或"商旅"' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '入住', '居家信息：商用住宅禁止出现入住描述', '删除或改为"进驻"或"入驻"' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '常住', '居家信息：商用住宅禁止常住描述', '删除或改为"长租"或"驻点"' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '起居', '居家信息：商用住宅禁止起居描述', '删除相关表述' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '做饭', '居家信息：商用住宅禁止做饭描述', '删除或改为"简餐"或"餐饮配套"' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '晾衣', '居家信息：商用住宅禁止晾衣相关描述', '删除相关表述' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '睡觉', '居家信息：商用住宅禁止睡觉相关描述', '删除或改为"休息区"' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '午休', '居家信息：商用住宅禁止午休相关描述', '删除或改为"休憩"' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '家居', '居家信息：商用住宅禁止家居描述', '删除或改为"办公家具"或"商用陈设"' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '家电', '居家信息：商用住宅禁止家电描述', '删除或改为"设备"' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '炊具', '居家信息：商用住宅禁止炊具描述', '删除相关表述' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '床品', '居家信息：商用住宅禁止床品描述', '删除相关表述' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '租房', '居家信息：商用住宅禁止租房描述', '删除或改为"租赁"' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '合租', '居家信息：商用住宅禁止合租描述', '删除相关表述' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '室友', '居家信息：商用住宅禁止室友描述', '删除相关表述' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '洗手间', '居家信息：商用住宅禁止洗手间描述', '删除或改为"卫生间"' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '马桶', '居家信息：商用住宅禁止马桶描述', '删除相关表述' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '淋浴', '居家信息：商用住宅禁止淋浴描述', '删除或改为"洗浴"' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '阳台', '居家信息：商用住宅禁止阳台描述', '如为居住阳台请删除，商用阳台可保留' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '玄关', '居家信息：商用住宅禁止玄关描述', '删除或改为"入口"或"接待区"' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '书房', '居家信息：商用住宅禁止书房描述', '删除或改为"办公区"或"会议室"' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '儿童房', '居家信息：商用住宅禁止儿童房描述', '删除相关表述' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '老人房', '居家信息：商用住宅禁止老人房描述', '删除相关表述' FROM projects WHERE code = 'shangu'
UNION ALL SELECT id, 'violation', '宠物', '居家信息：商用住宅禁止宠物相关描述', '删除相关表述' FROM projects WHERE code = 'shangu';

-- 4. 插入通用违规 (给两个项目都加上)
INSERT INTO rules (project_id, type, keyword, reason, suggestion) 
SELECT id, 'violation', '虽然.*但但', '关联词错误', '检查关联词搭配是否正确' FROM projects WHERE code IN ('haichen', 'shangu')
UNION ALL SELECT id, 'violation', '因为.*所以所以', '关联词错误', '检查关联词搭配是否正确' FROM projects WHERE code IN ('haichen', 'shangu')
UNION ALL SELECT id, 'violation', '既然.*就就', '关联词错误', '检查关联词搭配是否正确' FROM projects WHERE code IN ('haichen', 'shangu');
